import os
os.environ["COGNEE_SKIP_CONNECTION_TEST"] = "true"
import logging
import asyncio
from typing import List, Dict, Any
import cognee
from cognee.api.v1.search import SearchType

logger = logging.getLogger(__name__)

# Using default weights since we don't have user profiles right now
MEMORY_WEIGHTS = {
    "default": 1.0
}

async def setup_cognee():
    """Initialize cognee and connect to the cloud tenant."""
    api_key = os.environ.get("COGNEE_API_KEY")
    base_url = os.environ.get("COGNEE_BASE_URL")
    tenant_id = os.environ.get("COGNEE_TENANT_ID")
    
    if api_key and base_url:
        try:
            logger.info(f"Connecting Cognee SDK to Cloud Tenant at {base_url}...")
            # cognee.serve points the local SDK to the remote AWS tenant
            await cognee.serve(url=base_url, api_key=api_key)
            logger.info("Successfully connected Cognee SDK to Cloud.")
        except Exception as e:
            logger.error(f"Failed to connect to Cognee Cloud: {e}")
            raise
    else:
        logger.warning("Cognee Cloud credentials not found in .env, attempting local (which may fail due to LLM limits).")
        # In this mode we would set local config, but user is on cloud.
        pass

async def add_memory(chunk_data: Dict[str, Any], dataset_name: str = "kyro_memories"):
    """
    Add a chunk of memory to Cognee.
    Cognee Cloud manages the graph generation pipeline remotely.
    """
    text = chunk_data.get("text", "")
    if not text:
        return
        
    try:
        # 1. Upload data to Cloud
        await cognee.add(text, dataset_name=dataset_name)
        # 2. Trigger graph processing on Cloud
        await cognee.cognify(datasets=dataset_name)
        logger.info(f"Successfully added memory to Cognee dataset: {dataset_name}")
    except Exception as e:
        logger.error(f"Error adding memory to Cognee: {e}")
        raise

async def search_memories(query: str, dataset_name: str = "kyro_memories", limit: int = 5) -> List[Dict[str, Any]]:
    """
    Search memories using Cognee Cloud.
    """
    try:
        # Search directly returns insights generated by the Cloud's LLM pipeline
        results = await cognee.search(query_text=query, query_type=SearchType.RAG_COMPLETION, datasets=[dataset_name])
        
        final_results = []
        for item in results:
            # Parse the response dynamically depending on what the SDK returns
            if isinstance(item, dict):
                text = item.get("text", str(item))
                mem_id = item.get("id", str(item))
                score = item.get("score", 1.0)
            else:
                text = str(item)
                mem_id = str(item)
                score = 1.0
                
            weight = MEMORY_WEIGHTS.get(mem_id, 1.0)
            final_results.append({
                "text": text,
                "weight": weight,
                "score": score * weight,
                "id": mem_id
            })
            
        return sorted(final_results, key=lambda x: x["score"], reverse=True)[:limit]
    except Exception as e:
        logger.error(f"Error searching memories in Cognee: {e}")
        return []

async def get_graph_data(dataset_name: str = "kyro_memories") -> Dict[str, Any]:
    """
    (Placeholder) Cloud Graph retrieval might require specific endpoints.
    For now, we return empty nodes.
    """
    return {"nodes": [], "edges": []}

async def prune_stale_memories(days: int = 30):
    """
    (Placeholder) Prune old memories.
    """
    logger.info(f"Prune stale memories requested for {days} days.")
